package bases_de_datos_Entornos;

import java.io.Serializable;

/**
 * Model class of cargo_empleado.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CargoEmpleadoPrimeraBasededatos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Empleado. */
	private EmpleadoPrimeraBasededatos empleado;

	/** new_table. */
	private NewTablePrimeraBasededatos newTable;

	/**
	 * Constructor.
	 */
	public CargoEmpleadoPrimeraBasededatos() {
	}

	/**
	 * Set the Empleado.
	 * 
	 * @param empleado
	 *            Empleado
	 */
	public void setEmpleado(EmpleadoPrimeraBasededatos empleado) {
		this.empleado = empleado;
	}

	/**
	 * Get the Empleado.
	 * 
	 * @return Empleado
	 */
	public EmpleadoPrimeraBasededatos getEmpleado() {
		return this.empleado;
	}

	/**
	 * Set the new_table.
	 * 
	 * @param newTable
	 *            new_table
	 */
	public void setNewTable(NewTablePrimeraBasededatos newTable) {
		this.newTable = newTable;
	}

	/**
	 * Get the new_table.
	 * 
	 * @return new_table
	 */
	public NewTablePrimeraBasededatos getNewTable() {
		return this.newTable;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empleado == null) ? 0 : empleado.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CargoEmpleadoPrimeraBasededatos other = (CargoEmpleadoPrimeraBasededatos) obj;
		if (empleado == null) {
			if (other.empleado != null) {
				return false;
			}
		} else if (!empleado.equals(other.empleado)) {
			return false;
		}
		return true;
	}

}
