package bases_de_datos_Entornos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Empleado.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmpleadoPrimeraBasededatos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** numero_empleado. */
	private Integer numeroEmpleado;

	/** nombre. */
	private String nombre;

	/** The set of cargo_empleado. */
	private Set<CargoEmpleadoPrimeraBasededatos> cargoEmpleadoSet;

	/**
	 * Constructor.
	 */
	public EmpleadoPrimeraBasededatos() {
		this.cargoEmpleadoSet = new HashSet<CargoEmpleadoPrimeraBasededatos>();
	}

	/**
	 * Set the numero_empleado.
	 * 
	 * @param numeroEmpleado
	 *            numero_empleado
	 */
	public void setNumeroEmpleado(Integer numeroEmpleado) {
		this.numeroEmpleado = numeroEmpleado;
	}

	/**
	 * Get the numero_empleado.
	 * 
	 * @return numero_empleado
	 */
	public Integer getNumeroEmpleado() {
		return this.numeroEmpleado;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the set of the cargo_empleado.
	 * 
	 * @param cargoEmpleadoSet
	 *            The set of cargo_empleado
	 */
	public void setCargoEmpleadoSet(Set<CargoEmpleadoPrimeraBasededatos> cargoEmpleadoSet) {
		this.cargoEmpleadoSet = cargoEmpleadoSet;
	}

	/**
	 * Add the cargo_empleado.
	 * 
	 * @param cargoEmpleado
	 *            cargo_empleado
	 */
	public void addCargoEmpleado(CargoEmpleadoPrimeraBasededatos cargoEmpleado) {
		this.cargoEmpleadoSet.add(cargoEmpleado);
	}

	/**
	 * Get the set of the cargo_empleado.
	 * 
	 * @return The set of cargo_empleado
	 */
	public Set<CargoEmpleadoPrimeraBasededatos> getCargoEmpleadoSet() {
		return this.cargoEmpleadoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numeroEmpleado == null) ? 0 : numeroEmpleado.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmpleadoPrimeraBasededatos other = (EmpleadoPrimeraBasededatos) obj;
		if (numeroEmpleado == null) {
			if (other.numeroEmpleado != null) {
				return false;
			}
		} else if (!numeroEmpleado.equals(other.numeroEmpleado)) {
			return false;
		}
		return true;
	}

}
