package bases_de_datos_Entornos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of new_table.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NewTablePrimeraBasededatos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** cargo_id. */
	private Integer cargoId;

	/** nombre_cargo. */
	private String nombreCargo;

	/** The set of cargo_empleado. */
	private Set<CargoEmpleadoPrimeraBasededatos> cargoEmpleadoSet;

	/**
	 * Constructor.
	 */
	public NewTablePrimeraBasededatos() {
		this.cargoEmpleadoSet = new HashSet<CargoEmpleadoPrimeraBasededatos>();
	}

	/**
	 * Set the cargo_id.
	 * 
	 * @param cargoId
	 *            cargo_id
	 */
	public void setCargoId(Integer cargoId) {
		this.cargoId = cargoId;
	}

	/**
	 * Get the cargo_id.
	 * 
	 * @return cargo_id
	 */
	public Integer getCargoId() {
		return this.cargoId;
	}

	/**
	 * Set the nombre_cargo.
	 * 
	 * @param nombreCargo
	 *            nombre_cargo
	 */
	public void setNombreCargo(String nombreCargo) {
		this.nombreCargo = nombreCargo;
	}

	/**
	 * Get the nombre_cargo.
	 * 
	 * @return nombre_cargo
	 */
	public String getNombreCargo() {
		return this.nombreCargo;
	}

	/**
	 * Set the set of the cargo_empleado.
	 * 
	 * @param cargoEmpleadoSet
	 *            The set of cargo_empleado
	 */
	public void setCargoEmpleadoSet(Set<CargoEmpleadoPrimeraBasededatos> cargoEmpleadoSet) {
		this.cargoEmpleadoSet = cargoEmpleadoSet;
	}

	/**
	 * Add the cargo_empleado.
	 * 
	 * @param cargoEmpleado
	 *            cargo_empleado
	 */
	public void addCargoEmpleado(CargoEmpleadoPrimeraBasededatos cargoEmpleado) {
		this.cargoEmpleadoSet.add(cargoEmpleado);
	}

	/**
	 * Get the set of the cargo_empleado.
	 * 
	 * @return The set of cargo_empleado
	 */
	public Set<CargoEmpleadoPrimeraBasededatos> getCargoEmpleadoSet() {
		return this.cargoEmpleadoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cargoId == null) ? 0 : cargoId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NewTablePrimeraBasededatos other = (NewTablePrimeraBasededatos) obj;
		if (cargoId == null) {
			if (other.cargoId != null) {
				return false;
			}
		} else if (!cargoId.equals(other.cargoId)) {
			return false;
		}
		return true;
	}

}
